openapi: 3.0.3
info:
  title: GitLab Project Management API
  version: 1.0.0
  description: >
    Specifica OpenAPI 3.0 per la gestione dei progetti su GitLab.
servers:
  - url: https://gitlab.com/api/v4
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
security:
  - BearerAuth: []
paths:
  /projects:
    post:
      summary: Crea un nuovo progetto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                visibility:
                  type: string
                  enum: [private, internal, public]                  
              required: [name]
      responses:
        '201':
          description: Progetto creato

  /projects/{id}:
    get:
      summary: Ottieni i dettagli di un progetto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Dettagli del progetto
    put:
      summary: Aggiorna un progetto esistente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Progetto aggiornato
    delete:
      summary: Elimina un progetto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '202':
          description: Progetto in fase di eliminazione
