kind: RestDefinition
apiVersion: swaggergen.krateo.io/v1alpha1
metadata:
  name: gitlab-repo
  namespace: gitlab-test
spec: 
  oasPath: https://raw.githubusercontent.com/ldepandis/gitlab-openapi3/refs/heads/main/openapi3_small.yaml
  resourceGroup: gitlab.com
  resource: 
    kind: Repo
    identifiers:
    - id
    verbsDescription:
    - action: get
      method: GET
      path: /projects/{id}
    - action: update
      method: PUT
      path: /projects/{id}
    - action: delete
      method: DELETE
      path: /projects/{id}
    - action: create
      method: POST
      path: /projects
